name: shopper
description: ...
publish_to: 'none' # ! DO NOT REMOVE
version: 1.0.0+12

# SDK SETUP
environment:
  sdk: '>=3.1.4 <4.0.0'

# DEPENDENCIES
dependencies:
  animations: ^2.0.8
  another_flushbar: ^1.12.30
  avatar_glow: ^3.0.1
  barcode_widget: ^2.0.4
  easy_localization: ^3.0.3
  equatable: ^2.0.5
  event_bus: ^2.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.4.0
  flutter_bloc: ^8.1.3
  flutter_slidable:
    path: ./packages/flutter_slidable-3.0.1/
  flutter_svg: ^2.0.9
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  hive_flutter: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  loading_animation_widget: ^1.2.0+4
  lottie: ^2.7.0
  mailer: ^6.0.1
  mixpanel_flutter: ^2.2.0
  mobile_scanner: ^3.5.6
  multiple_result: ^5.1.0
  once: ^1.6.0
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  speech_to_text: ^6.5.1
  store_redirect: ^2.0.1
  supabase_flutter: ^2.0.1
  url_launcher: ^6.2.3
  uuid: ^4.1.0

# DEV DEPENDENCIES
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# ICONS, FONTS, SHARED
flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/icons/
    - assets/list_icons/
    - assets/app/
    - assets/fonts/
    - assets/lottie/
