name: swipehr
description: ...
publish_to: 'none' #! DO NOT TOUCH

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  easy_localization: ^3.0.3
  equatable: ^2.0.5
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_card_swiper: ^6.0.0
  flutter_pdfview: ^1.3.2
  flutter_svg: ^2.0.9
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  internet_connection_checker: ^1.0.0+1
  ionicons: ^0.2.2
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  supabase_flutter: ^1.10.25
  uuid: ^4.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
